# Generated by Django 4.2.5 on 2023-11-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_streaks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streak',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='streak',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='streak',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
