# Generated by Django 4.2.5 on 2023-11-05 15:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_streaks', '0002_remove_streak_end_date_remove_streak_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='streak',
            name='start_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
