# Generated by Django 4.2.5 on 2023-11-08 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_streaks', '0004_streak_latest_streak_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='streak',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
